name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Run CI
        run: npm i && npm run ci
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/.nyc_output/coverage/lcov.info
