name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run CI
        run: npm i && npm run ci
      - name: Upload Coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ${{ github.workspace }}/.nyc_output/coverage/lcov.info
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
