name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm i
      - run: npm run ci
        env:
          CI: true
      - name: Upload Coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ${{ github.workspace }}/.nyc_output
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
